/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package bucket.quiz

import io.javalin.Javalin

fun main() {
  val app = Javalin.create().get("/") { ctx -> ctx.result("Hello World") }.start(7070)
}
