/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package bucket.quiz

import bucket.quiz.models.ApplicationRoute
import bucket.quiz.models.QuizCategory
import io.javalin.Javalin

fun main() {
  Javalin.create()
    .get("${ApplicationRoute.QUESTION.route}/category/all") { it.json(QuizCategory.values()) }
    .start(7070)
}
